/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerAlternativesRouteImport } from './routes/farmer.alternatives'
import { Route as FarmerCropRouteImport } from './routes/farmer.crop'
import { Route as FarmerProcurementRouteImport } from './routes/farmer.procurement'
import { Route as FarmerQueueRouteImport } from './routes/farmer.queue'
import { Route as FarmerReportDelayRouteImport } from './routes/farmer.report-delay'
import { Route as FarmerSlotRouteImport } from './routes/farmer.slot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAlternativesRoute = FarmerAlternativesRouteImport.update({
  id: '/alternatives',
  path: '/alternatives',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCropRoute = FarmerCropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProcurementRoute = FarmerProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerQueueRoute = FarmerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerReportDelayRoute = FarmerReportDelayRouteImport.update({
  id: '/report-delay',
  path: '/report-delay',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSlotRoute = FarmerSlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/farmer/alternatives': typeof FarmerAlternativesRoute
  '/farmer/crop': typeof FarmerCropRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/farmer/report-delay': typeof FarmerReportDelayRoute
  '/farmer/slot': typeof FarmerSlotRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmer/alternatives': typeof FarmerAlternativesRoute
  '/farmer/crop': typeof FarmerCropRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/farmer/report-delay': typeof FarmerReportDelayRoute
  '/farmer/slot': typeof FarmerSlotRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/farmer/alternatives': typeof FarmerAlternativesRoute
  '/farmer/crop': typeof FarmerCropRoute
  '/farmer/procurement': typeof FarmerProcurementRoute
  '/farmer/queue': typeof FarmerQueueRoute
  '/farmer/report-delay': typeof FarmerReportDelayRoute
  '/farmer/slot': typeof FarmerSlotRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer'
    | '/farmer/alternatives'
    | '/farmer/crop'
    | '/farmer/procurement'
    | '/farmer/queue'
    | '/farmer/report-delay'
    | '/farmer/slot'
    | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/farmer/alternatives'
    | '/farmer/crop'
    | '/farmer/procurement'
    | '/farmer/queue'
    | '/farmer/report-delay'
    | '/farmer/slot'
    | '/farmer'
  id:
    | '__root__'
    | '/'
    | '/farmer'
    | '/farmer/alternatives'
    | '/farmer/crop'
    | '/farmer/procurement'
    | '/farmer/queue'
    | '/farmer/report-delay'
    | '/farmer/slot'
    | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/alternatives': {
      id: '/farmer/alternatives'
      path: '/alternatives'
      fullPath: '/farmer/alternatives'
      preLoaderRoute: typeof FarmerAlternativesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/crop': {
      id: '/farmer/crop'
      path: '/crop'
      fullPath: '/farmer/crop'
      preLoaderRoute: typeof FarmerCropRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/procurement': {
      id: '/farmer/procurement'
      path: '/procurement'
      fullPath: '/farmer/procurement'
      preLoaderRoute: typeof FarmerProcurementRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/queue': {
      id: '/farmer/queue'
      path: '/queue'
      fullPath: '/farmer/queue'
      preLoaderRoute: typeof FarmerQueueRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/report-delay': {
      id: '/farmer/report-delay'
      path: '/report-delay'
      fullPath: '/farmer/report-delay'
      preLoaderRoute: typeof FarmerReportDelayRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/slot': {
      id: '/farmer/slot'
      path: '/slot'
      fullPath: '/farmer/slot'
      preLoaderRoute: typeof FarmerSlotRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerAlternativesRoute: typeof FarmerAlternativesRoute
  FarmerCropRoute: typeof FarmerCropRoute
  FarmerProcurementRoute: typeof FarmerProcurementRoute
  FarmerQueueRoute: typeof FarmerQueueRoute
  FarmerReportDelayRoute: typeof FarmerReportDelayRoute
  FarmerSlotRoute: typeof FarmerSlotRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAlternativesRoute: FarmerAlternativesRoute,
  FarmerCropRoute: FarmerCropRoute,
  FarmerProcurementRoute: FarmerProcurementRoute,
  FarmerQueueRoute: FarmerQueueRoute,
  FarmerReportDelayRoute: FarmerReportDelayRoute,
  FarmerSlotRoute: FarmerSlotRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
